<?php
/** @var \MageSuite\FileAttachments\Block\Adminhtml\Attachment\AssignFileAttachments $block */
/** @var \MageSuite\FileAttachments\Block\Adminhtml\Attachment\Tab\Attachment $blockGrid */
$blockGrid = $block->getBlockGrid();
$gridJsObjectName = $blockGrid->getJsObjectName();
?>
<?= $block->getGridHtml(); ?>
<input type="hidden" name="file_attachments" id="file_attachments" data-form-part="product_form"/>
<script type="text/x-magento-init">
    {
        "*": {
            "MageSuite_FileAttachments/catalog/product/assign-file-attachments": {
                "selectedAttachments": <?= /* @noEscape */ $block->getSelectedAttachmentsJson(); ?>,
                "gridJsObjectName": <?= /* @noEscape */ '"' . $gridJsObjectName . '"' ?: '{}'; ?>
            }
        }
    }
</script>
<!-- @todo remove when "UI components" will support such initialization -->
<script>
    require('mage/apply/main').apply();
</script>
