<?php
/**
 * @var $block \Magento\Framework\View\Element\Template
 * @var $escaper Magento\Framework\Escaper
 * @var $viewModel \MageSuite\FileAttachments\ViewModel\Product\Attachment
 * @var $attachments \MageSuite\FileAttachments\Api\Data\AttachmentInterface[]
 */
$viewModel = $block->getViewModel();
$attachments = $viewModel->getAttachments();
?>

<?php if (count($attachments)) :?>
    <ul class="cs-attachments">
        <?php foreach ($attachments as $attachment) : ?>
            <?php
            $downloadUrl = $attachment->getDownloadUrl();
            $name = $attachment->getName() ?? $downloadUrl;
            $description = $attachment->getDescription() ?? null;
            $thumbnailUrl = $attachment->getThumbnailUrl();
            ?>
            <li class="cs-attachments__item">
                <a class="cs-attachments__link" href="<?= $escaper->escapeHtml($downloadUrl) ?>">
                    <?php if ($thumbnailUrl) :?>
                        <img class="cs-attachments__thumbnail" src="<?= /* @noEscape */ $attachment->getThumbnailUrl() ?>" />
                    <?php else : ?>
                        <?= $this->getLayout() //phpcs:ignore
                            ->createBlock(\MageSuite\ThemeHelpers\Block\Icon::class)
                            ->setIconUrl('images/icons/attachment.svg')
                            ->setCssClass('cs-attachments__thumbnail cs-attachments__thumbnail--placeholder')
                            ->setInlined(true)
                            ->toHtml();
                        ?>
                    <?php endif; ?>
                    <span class="cs-attachments__texts">
                        <span class="cs-attachments__name"><?= $escaper->escapeHtml($name) ?></span>
                        <?php if ($description) :?>
                            <span class="cs-attachments__description"><?= $escaper->escapeHtml($description) ?></span>
                        <?php endif; ?>
                    </span>
                    <span class="cs-attachments__download"></span>
                </a>
            </li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>
