<?php
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \MageSuite\FileAttachments\ViewModel\Product\Attachment $viewModel */
/** @var \MageSuite\FileAttachments\Api\Data\AttachmentInterface[] $attachments */
$viewModel = $block->getViewModel();
$attachments = $viewModel->getAttachments();
?>

<?php if (count($attachments)) :?>
    <ul class="cs-attachments">
        <?php foreach ($attachments as $attachment) : ?>
            <?php
            $fileUrl = $attachment->getFileUrl();
            $name = $attachment->getName() ?? $fileUrl;
            $description = $attachment->getDescription() ?? null;
            $thumbnailUrl = $attachment->getThumbnailUrl();
            ?>
            <li class="cs-attachments__item">
                <a class="cs-attachments__link" href="<?= $escaper->escapeHtml($fileUrl) ?>" download>
                    <?php if ($thumbnailUrl) :?>
                        <img class="cs-attachments__thumbnail" url="<?= $attachment->getThumbnailUrl() ?>" />
                    <?php else: ?>
                        <?= $this->getLayout() //phpcs:ignore
                            ->createBlock(\MageSuite\ThemeHelpers\Block\Icon::class)
                            ->setIconUrl('images/icons/file.svg')
                            ->setCssClass('cs-attachments__thumbnail')
                            ->setInlined(true)
                            ->toHtml();
                        ?>
                    <?php endif; ?>
                    <span class="cs-attachments__texts">
                        <span class="cs-attachments__name"><?= $escaper->escapeHtml($name) ?></span>
                        <?php if ($description) :?>
                            <span class="cs-attachments__description"><?= $escaper->escapeHtml($description) ?></span>
                        <?php endif; ?>
                    </span>
                    <span class="cs-attachments__download"></span>
                </a>
            </li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>
